Repository devping-kr/NNplanner-FE, pull requests merged in 2024-09, with the labels that each got.

#16 Feat[#THKV-20]: TableHeader, TableBody 구현 및 Table에 적용
  src/app/woorim/page.tsx
  src/components/common/Table/index.tsx
  src/components/common/TableBody/index.tsx
  src/components/common/TableHeader/index.tsx
Labels: 공통 컴포넌트

#21 Feat[#THKV-28] : 아이콘 컴포넌트 추가, 아이콘 교체
  src/components/common/Icon/assets/ArrowNext.tsx
  src/components/common/Icon/assets/ArrowPrev.tsx
  src/components/common/Icon/assets/Auto.tsx
  src/components/common/Icon/assets/Calendar.tsx
  src/components/common/Icon/assets/Chart.tsx
  src/components/common/Icon/assets/Dashboard.tsx
  src/components/common/Icon/assets/Logout.tsx
  src/components/common/Icon/assets/Search.tsx
  src/components/common/Icon/assets/Warning.tsx
  src/styles/colors.ts
Labels: 공통 컴포넌트

#20 Feat[#THKV-23] : Navbar 구현 및 Icon 수정 등
  public/imgs/navbar-logo.png
  src/app/globals.css
  src/app/woorim/page.tsx
  src/components/common/Divider/index.tsx
  src/components/common/Icon/assets/Logout.tsx
  src/components/common/Icon/assets/index.ts
  src/components/common/Icon/index.tsx
  src/components/common/NavMenu/NavMenu.variant.tsx
  src/components/common/NavMenu/index.tsx
  src/components/common/NavProfile/index.tsx
  src/components/common/Navbar/index.tsx
  src/constants/_navbar.ts
Labels: 공통 컴포넌트

#32 Fix[#THKV-41] : 공통 컴포넌트 (root)/layout, Button, SelectButton, Calendar, CalendarDay 수정
  src/app/(root)/layout.tsx
  src/components/common/Button/Button.variant.tsx
  src/components/common/Calendar/Calendar.variant.tsx
  src/components/common/Calendar/index.tsx
  src/components/common/CalendarDay/index.tsx
  src/components/common/SelectButton/SelectButton.variant.tsx
  src/components/common/SelectButton/index.tsx
  src/components/common/Selectbox/index.tsx
Labels: bug, ASAP

#36 feat[#THKV-43]: 설문 상세페이지 구현
  package-lock.json
  package.json
  src/app/(root)/viewChart/[id]/page.tsx
  src/components/common/Typography/index.tsx
  src/components/feature/ChartDetail/index.tsx
  src/components/shared/ChartDetail/AverageCard/index.tsx
  src/components/shared/ChartDetail/AverageGraph/index.tsx
  src/components/shared/ChartDetail/BarGraph/index.tsx
  src/components/shared/ChartDetail/TextList/index.tsx
  src/components/shared/ChartDetail/TopCard/index.tsx
  src/constants/_detailSurvey.ts
Labels: 공통 컴포넌트, 기능 구현

#35 Feat[#THKV-39] : 자동 식단 작성(기본, 생성, 수정) 페이지 구현
  src/app/(root)/autoPlan/create/page.tsx
  src/app/(root)/autoPlan/edit/page.tsx
  src/app/(root)/autoPlan/page.tsx
  src/components/common/Calendar/Calendar.variant.tsx
  src/components/common/Calendar/index.tsx
  src/components/common/Icon/assets/Edit.tsx
  src/components/common/Input/Input.variant.tsx
  src/components/common/Selectbox/index.tsx
  src/components/common/Table/index.tsx
  src/components/common/TableBody/index.tsx
  src/components/common/TableHeader/index.tsx
  src/components/common/Typography/Typography.variant.tsx
  src/components/common/Typography/index.tsx
  src/components/feature/AutoPlan/index.tsx
  src/components/feature/AutoPlanCreate/index.tsx
  src/components/feature/AutoPlanEdit/index.tsx
  src/components/shared/Meal/KcalInfo/index.tsx
  src/components/shared/Meal/MealCalender/index.tsx
  src/components/shared/Meal/MealCreateHeader/index.tsx
  src/components/shared/Meal/MealEdit/index.tsx
  src/components/shared/Meal/MealHeader/index.tsx
  src/components/shared/Meal/MealInfoContainer/index.tsx
  src/components/shared/Meal/MealTable/index.tsx
  src/components/shared/Meal/NutritionInfo/index.tsx
  src/constants/_calendarData.ts
  src/constants/_category.ts
  src/constants/_schema.ts
  src/schema/mealSchema.ts
  src/type/mealType.ts
  src/utils/calendar.ts
Labels: 공통 컴포넌트, 기능 구현

#41 Refactor[#THKV-50] : TableHeader, Navbar, Button 컴포넌트 수정
  src/components/common/Icon/assets/index.ts
  src/components/common/Navbar/index.tsx
  src/components/common/TableHeader/index.tsx
Labels: 리팩터링

#40 Refactor[#THKV-49] : 자동식단 페이지 수정사항 반영
  src/components/common/Calendar/index.tsx
  src/components/common/Icon/assets/index.ts
  src/components/common/InfoCard/index.tsx
  src/components/common/SelectButton/SelectButton.variant.tsx
  src/components/feature/AutoPlan/index.tsx
  src/components/feature/AutoPlanCreate/index.tsx
  src/components/feature/AutoPlanEdit/index.tsx
  src/components/shared/Meal/MealCalender/index.tsx
  src/components/shared/Meal/MealCreateHeader/index.tsx
  src/components/shared/Meal/MealEdit/index.tsx
  src/components/shared/Meal/MealHeader/index.tsx
  src/components/shared/Meal/MealInfoContainer/index.tsx
  src/components/shared/Meal/MealTable/index.tsx
Labels: 공통 컴포넌트, 기능 구현, 리팩터링

#44 Fix[#THKV-53]: Toast, Calendar 수정 및 폰트 적용
  .husky/pre-push
  next.config.mjs
  public/fonts/PretendardVariable.woff2
  src/app/globals.css
  src/app/layout.tsx
  src/assets/.gitkeep
  src/components/common/Calendar/index.tsx
  src/components/common/Toast/index.tsx
  src/components/shared/Survey/CustomDatePickerHeader/index.tsx
  src/constants/.gitkeep
  src/lib/.gitkeep
  src/schema/.gitkeep
  src/stores/.gitkeep
  src/styles/.gitkeep
  src/type/.gitkeep
  src/utils/.gitkeep
Labels: 리팩터링
